### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kellieotto** [iagolemos1/thresholdmodeling#5]
This is part of your [JOSS review](https://github.com/openjournals/joss-reviews/issues/2013).

[This file is called test.py](https://github.com/iagolemos1/thresholdmodeling/blob/master/Test/test.py), but these aren't unit tests. Unit tests check that the code is producing the output that you expect. [This site](https://realpython.com/python-testing/) has detailed examples on how to write tests.

The expectation from JOSS is this: Are there automated tests or manual steps described so that the functionality of the software can be verified?

**Comment by iagolemos1** [comment]
@kellieotto The file test is just something I used to test the functions. The main idea for the expectation from JOSS is in the README, where I describe, with steps, the funcionality of the software. Isn't that enough? because if it not, I will provide an automated test.

**Comment by iagolemos1** [comment]
@kellieotto I am just confused with unit testing. The functions from ``thresholdmodeling`` are quite unpredictable, I mean, for example, how am I going to write a unittest for the Parameter_Stability_Function if it uses the log-likelihood function several times with reparameterization of an estimated parameter in order to draw a graphic? The only way I see it is taking the answer a calling the test for the given data and compare it to the answer. Please, help me to clarify this :P

**Comment by iagolemos1** [comment]
Now I understand what it supposed to be. I don't know exactly what I should do. The package functions are quite unpredictable, I mean, it is hard to test what functions that will compute estimatives of the log-likelihood function several times to give an answer will return, like the Parameter_Stability_Function. 
When I wrote the README, the idea was to give the answers presented in the Coles's book. I mean, they are manual steps, right? If anyone goes to the book, the answers in the README can be verified, and if anyone reproduce the steps and get that results, the software functionality can be also verified.

**Comment by iagolemos1** [comment]
Also, there are some functions that we can't verify by Coles's book. But we can verify that using another packages from R, for example. I already did that when I was writing. What do you think about that?

**Comment by iagolemos1** [comment]
Just changed the folder and file name to avoid confusion with testing.

**Comment by iagolemos1** [comment]
@kellieotto while I wait for you answer for the plots, I wrote some unittest codes for numerical values. I ran this in Travis CI but I having problems because it's not running at test. I am receving this at the final: 
![image](https://user-images.githubusercontent.com/57317828/73126715-be619f80-3f94-11ea-947a-7be5e3ad1fee.png)
I needed to made a little change in the source code to make it works.

**Comment by iagolemos1** [comment]
Now the automated tests are running as it should be. 
![image](https://user-images.githubusercontent.com/57317828/73128784-58384500-3fb3-11ea-9629-f221666bf04d.png)

**Comment by kellieotto** [comment]
@iagolemos1 The unit tests you wrote in the tests/ directory look good! I understand you can't write tests for plots, but checking the numeric values are what you expect from the Cole examples is good 👍

**Comment by iagolemos1** [comment]
@kellieotto Thanks!
